FROM node:14-alpine as build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:14-alpine as production
WORKDIR /app

COPY package*.json ./
RUN npm ci --production

COPY --from=build /app/dist /app/dist

ENV DB_PORT 3500

# Expose the application port
EXPOSE 3500

# Start the application
CMD ["node", "dist/app.js"]