version: '3.9'
services:
  postgres-db:
    image: "postgres:15.4-alpine"
    container_name: "node-gmp-db"
    environment:
      - POSTGRES_USER=node_gmp
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=node_gmp
    restart: always
    ports:
      - 5432:5432