version: "3.9"
services:
  mongo:
    image: "mongo"
    container_name: "mongoDB"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    restart: always
    ports:
      - 27017:27017
    logging:
      options:
        max-size: 1g
